[project]
name = "ha-tibber-prices"
version = "1.0.0"
description = "Tibber Prices Custom Integration for Home Assistant"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=6.0.0,<7.0.0",
    "pytest-homeassistant-custom-component>=0.13.195",
    "ruff>=0.15.1",
]
